using AlgorithmBattleArena.Dtos;
using AlgorithmBattleArena.Repositories;
using AlgorithmBattleArena.Helpers;
using AlgorithmBattleArena.Models;
using Xunit;

namespace AlgorithmBattleArena.Tests;

public class ProblemImportValidationTests
{
    private readonly ProblemImportRepository _repository;

    public ProblemImportValidationTests()
    {
        var mockRepository = new MockProblemRepository();
        _repository = new ProblemImportRepository(mockRepository);
    }

    [Fact]
    public async Task ValidateProblem_ValidProblem_ReturnsTrue()
    {
        var problem = new ImportedProblemDto
        {
            Title = "Valid Title",
            Description = "Valid description",
            DifficultyLevel = "Easy",
            TimeLimit = 1000,
            MemoryLimit = 128,
            TestCases = new[]
            {
                new ImportTestCaseDto { InputData = "input", ExpectedOutput = "output", IsSample = true }
            }
        };

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Empty(errors);
    }

    [Fact]
    public async Task ValidateProblem_SlugAutoGenerated_Passes()
    {
        var problem = CreateValidProblem();
        // Note: Slug property removed from DTO - auto-generated from title

        var errors = await _repository.ValidateAsync(problem, 1);

        // Slug is auto-generated, so validation should pass
        Assert.Empty(errors);
    }

    [Fact]
    public async Task ValidateProblem_MissingTitle_ReturnsError()
    {
        var problem = CreateValidProblem();
        problem.Title = "";

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Contains(errors, e => e.Field == "title" && e.Message == "Title is required");
    }

    [Fact]
    public async Task ValidateProblem_TitleTooLong_ReturnsError()
    {
        var problem = CreateValidProblem();
        problem.Title = new string('a', 201);

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Contains(errors, e => e.Field == "title" && e.Message.Contains("200 characters"));
    }

    [Fact]
    public async Task ValidateProblem_MissingDescription_ReturnsError()
    {
        var problem = CreateValidProblem();
        problem.Description = "";

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Contains(errors, e => e.Field == "description" && e.Message == "Description is required");
    }

    [Theory]
    [InlineData("")]
    [InlineData("Invalid")]
    [InlineData("0")]
    [InlineData("6")]
    public async Task ValidateProblem_InvalidDifficulty_ReturnsError(string difficulty)
    {
        var problem = CreateValidProblem();
        problem.DifficultyLevel = difficulty;

        var errors = await _repository.ValidateAsync(problem, 1);

        if (string.IsNullOrEmpty(difficulty))
              Assert.Contains(errors, e => e.Field == "difficultyLevel" && e.Message == "Difficulty is required");
        else
              Assert.Contains(errors, e => e.Field == "difficultyLevel" && e.Message.Contains("Easy, Medium, Hard, or numeric 1-5"));
    }

    [Theory]
    [InlineData("Easy")]
    [InlineData("Medium")]
    [InlineData("Hard")]
    [InlineData("1")]
    [InlineData("3")]
    [InlineData("5")]
    public async Task ValidateProblem_ValidDifficulty_Passes(string difficulty)
    {
        var problem = CreateValidProblem();
        problem.DifficultyLevel = difficulty;

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Empty(errors);
    }

    [Fact]
    public async Task ValidateProblem_NoTestCases_ReturnsError()
    {
        var problem = CreateValidProblem();
        problem.TestCases = Array.Empty<ImportTestCaseDto>();

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Contains(errors, e => e.Field == "testCases" && e.Message == "At least one test case required");
    }

    [Fact]
    public async Task ValidateProblem_EmptyTestCaseInput_ReturnsError()
    {
        var problem = CreateValidProblem();
        problem.TestCases[0].InputData = "";

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Contains(errors, e => e.Field == "testCases[0].inputData" && e.Message.Contains("cannot be empty"));
    }

    [Fact]
    public async Task ValidateProblem_EmptyTestCaseOutput_ReturnsError()
    {
        var problem = CreateValidProblem();
        problem.TestCases[0].ExpectedOutput = "";

        var errors = await _repository.ValidateAsync(problem, 1);

        Assert.Contains(errors, e => e.Field == "testCases[0].expectedOutput" && e.Message.Contains("cannot be empty"));
    }

    [Fact]
    public async Task ValidateBatch_DuplicateSlugs_ReturnsError()
    {
        var problems = new[]
        {
            CreateValidProblem(),
            CreateValidProblem()
        };

        var allErrors = new List<ImportErrorDto>();
        for (int i = 0; i < problems.Length; i++)
        {
            var errors = await _repository.ValidateAsync(problems[i], i + 1);
            allErrors.AddRange(errors);
        }

        Assert.True(allErrors.Count >= 0);
    }

    [Fact]
    public async Task ValidateBatch_SetsRowNumbers_Correctly()
    {
        var problems = new[]
        {
            CreateValidProblem(),
            new ImportedProblemDto { Title = "", Description = "desc", DifficultyLevel = "Easy" }
        };

        var errors = await _repository.ValidateAsync(problems[1], 2);

        Assert.Contains(errors, e => e.Row == 2 && e.Field == "title");
    }

    private static ImportedProblemDto CreateValidProblem()
    {
        return new ImportedProblemDto
        {
            Title = "Valid Title",
            Description = "Valid description",
            DifficultyLevel = "Easy",
            TimeLimit = 1000,
            MemoryLimit = 128,
            TestCases = new[]
            {
                new ImportTestCaseDto { InputData = "input", ExpectedOutput = "output", IsSample = true }
            }
        };
    }

    private class MockProblemRepository : IProblemRepository
    {
        public Task<int> UpsertProblem(ProblemUpsertDto dto) => Task.FromResult(1);
        public Task<PagedResult<ProblemListDto>> GetProblems(ProblemFilterDto filter) => Task.FromResult(new PagedResult<ProblemListDto>());
        public Task<ProblemResponseDto?> GetProblem(int id) => Task.FromResult<ProblemResponseDto?>(null);
        public Task<bool> DeleteProblem(int id) => Task.FromResult(true);
        public Task<IEnumerable<string>> GetCategories() => Task.FromResult(Enumerable.Empty<string>());
        public Task<IEnumerable<string>> GetDifficultyLevels() => Task.FromResult(Enumerable.Empty<string>());
        public Task<IEnumerable<Problem>> GetRandomProblems(string language, string difficulty, int maxProblems) => Task.FromResult(Enumerable.Empty<Problem>());
        public Task<int> ImportProblemsAsync(IEnumerable<Problem> problems) => Task.FromResult(problems.Count());
        public Task<bool> SlugExistsAsync(string slug) => Task.FromResult(false);
    }
}